# Generated by Django 5.0.3 on 2024-05-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_acting_dean',
            new_name='is_approver',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_dean',
            new_name='is_creator',
        ),
        migrations.AddField(
            model_name='subjectoutline',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
