# Generated by Django 5.0.3 on 2024-05-22 06:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_rename_is_acting_dean_user_is_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectoutline',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subjectoutline',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subjectoutline',
            name='document',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subjectoutline',
            name='regulation',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
