# Generated by Django 5.0.3 on 2024-05-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_subjectoutline_is_pending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_feedbacker',
        ),
    ]
