# Generated by Django 5.0.3 on 2024-05-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_remove_user_is_feedbacker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='insistence',
        ),
        migrations.AddField(
            model_name='subject',
            name='insistence',
            field=models.ManyToManyField(blank=True, null=True, to='MainApp.subject'),
        ),
    ]
