# Generated by Django 5.0.3 on 2024-05-24 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_remove_subject_insistence_subject_insistence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='insistence',
        ),
        migrations.AddField(
            model_name='subject',
            name='insistence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.subject'),
        ),
    ]
