# Generated by Django 5.0.3 on 2024-05-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_remove_subject_insistence_subject_insistence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectoutline',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
