# Generated by Django 5.0.3 on 2024-05-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_alter_subjectoutline_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectoutline',
            name='description',
            field=models.CharField(blank=True, max_length=8192),
        ),
    ]
