# Generated by Django 5.0.3 on 2024-05-25 11:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_subjectoutline_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectoutline',
            name='teaching_method',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subjectoutline',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
