# Generated by Django 5.0.3 on 2024-05-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_subjectoutline_teaching_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationtest',
            name='subject_standard',
        ),
        migrations.AddField(
            model_name='evaluationtest',
            name='subject_standard',
            field=models.ManyToManyField(to='MainApp.subjectoutcomestandard'),
        ),
    ]
