# Generated by Django 5.0.3 on 2024-05-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_remove_evaluationtest_subject_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationtest',
            name='subject_standard',
            field=models.ManyToManyField(blank=True, to='MainApp.subjectoutcomestandard'),
        ),
    ]
