# Generated by Django 5.0.3 on 2024-05-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_alter_evaluationtest_subject_standard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='subjectoutline',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='subjectoutline',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='subjectoutline',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], null=True),
        ),
    ]
