# Generated by Django 5.0.3 on 2024-05-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_alter_subjectoutline_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='insistence',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_insistence+', to='MainApp.subject'),
        ),
    ]
