# Generated by Django 5.0.3 on 2024-05-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_alter_subject_insistence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='insistence',
            field=models.ManyToManyField(blank=True, null=True, to='MainApp.subject'),
        ),
    ]
