# Generated by Django 5.0.3 on 2024-05-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0019_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
