# Generated by Django 5.0.3 on 2024-06-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_alter_comment_user_alter_subjectoutline_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_creator',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Creator'), (2, 'Approver')], default=0),
        ),
    ]
