# Generated by Django 5.0.3 on 2024-06-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0027_remove_user_is_approver_remove_user_is_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
    ]
